baseURL = "https://nickkeers.com"
languageCode = "en-us"
title = "Tech blog"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Nick Keers"

[params]
   author = "Nick Keers"
   description = "I'm a software engineer currently working in Infrastructure automation / platform engineering"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light"
   readMore = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true