languageCode: "en-us"
baseUrl: "http://nickkeers.com"
title: "Nick Keers - blog"
theme: "anubis"
paginate: 10
googleAnalytics: UA-176069915-1
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Nick Keers"
  description: "I'm a software engineer currently working in Infrastructure automation / platform engineering"
  customCSS:
    - css/my.css # relative path to "static" directory
  customJS:
    - js/main.js # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
